### ISSUE TITLE
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by cifar10** [zhouhaocv/RLM-Net#1]
hi,thanks your source code,When i run train_RLM_proposing_stage.py,I meet a error:
from maskrcnn_benchmark import _C
ImportError: /data-rbd/zdm/RLM-Net/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

my virtual environment is pytorch1.0.1、cudatoolkit9.0 
Can you help me with that and how to sovle it

**Comment by zhouhaocv** [comment]
Hi.
It seems like an error in maskrcnn-benchmark. Make sure to create a new env before you compile the maskrcnn, or you can follow the reply [#here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/119) for details :）

**Comment by lambda-001** [comment]
I have the same problem, how you solve it?@cifar10
