### ISSUE TITLE
No such file or directory: 'catalog://ImageNetPretrained/MSRA/R-50'

### ISSUE THREAD

**Issue by cifar10** [zhouhaocv/RLM-Net#2]
Hi，im sorry to bother you again,i have create virtual environment successfully,
 but when i run "python train_RLM_proposing_stage.py", 
it shows that :No such file or directory: 'catalog://ImageNetPretrained/MSRA/R-50'
So,could you help me with that, and need to download something?

**Comment by zhouhaocv** [comment]
That's pre-trained weights from ImageNet, you can download [it](https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl) into your local path and change the path in [model.weights](https://github.com/zhouhaocv/RLM-Net/blob/master/vrd/configs/RLM_Net_objectpairs_proposing_stage.yaml) . or you can also obtain maskrcnn provided [weights](https://download.pytorch.org/models/maskrcnn/e2e_faster_rcnn_R_50_FPN_1x.pth)  for better performances.

**Comment by cifar10** [comment]
Ok，got it, thank you very much
