### ISSUE TITLE
training with multi GPUs

### ISSUE THREAD

**Issue by cifar10** [zhouhaocv/RLM-Net#3]
Thanks your code，i have run it successfully.
But when i changed the GPU numbers in"os.environ["CUDA_VISIBLE_DEVICES"]" ,such as  os.environ["CUDA_VISIBLE_DEVICES"]='0,1'. The code also use one single GPU '0'. So how to make the code training with multi GPUs?  Thank you.

**Comment by zhouhaocv** [comment]
The current version is not supported by Muti-GPU training, perhaps I'll implement it in my spare time.
I guess using DataParallel will work :）
```
if torch.cuda.device_count() > 1:
   print("Use", torch.cuda.device_count(), "GPUs")
   model = nn.DataParallel(model)`    
model.to(device)
```
just have a try

**Comment by cifar10** [comment]
appreciate it very much
