### ISSUE TITLE
how to get A_sim.mat and obj2vec.mat

### ISSUE THREAD

**Issue by cifar10** [zhouhaocv/RLM-Net#4]
Hi, i want to use my dataset to run "python train_RLM_predicate_stage.py",but it needs A_sim.mat and obj2vec.mat, the old file belongs to VRD dataset. I want to know how to make my dataset's A_sim.mat and obj2vec.mat

**Comment by zhouhaocv** [comment]
obj2vec.mat contains pre-trained 300-dim word vectors of the object categories, you can use the Glove package to get your own word vectors easily.

If you wanna get your own A_sim,  you should generate spatial-anchors firstly, and then calculate the similarities between them. Just like the [demo code](https://github.com/zhouhaocv/RLM-Net/blob/master/vrd/generate_spatial_anchors_A_sim.py).

**Comment by cifar10** [comment]
appreciate it very much
